-- ══════════════════════════════════════════════════════════════
-- InstaPort TMS — Complete Supabase Schema
-- Run this ONCE in: Supabase Dashboard → SQL Editor → New Query → Run
-- ══════════════════════════════════════════════════════════════

-- Organizations / tenants
create table if not exists tenants (
  id text primary key,
  name text not null,
  plan text default 'starter',
  active boolean default true,
  created_at timestamptz default now()
);

-- Users (PINs stored as bcrypt hashes by the server)
create table if not exists users (
  id bigint generated by default as identity primary key,
  tenant_id text references tenants(id),
  employee_id text,
  name text not null,
  role text not null,
  pin text,
  email text,
  active boolean default true,
  created_at timestamptz default now()
);
create index if not exists idx_users_tenant on users(tenant_id);

-- Trips
create table if not exists trips (
  id text primary key,
  tenant_id text references tenants(id),
  customer text, type text, dir text, condition text,
  origin text, dests text, dests_arr jsonb,
  km numeric, cost numeric, co2 numeric, cost_breakdown jsonb,
  truck text, driver text, driver_note text,
  actual_km numeric, status text,
  checklist jsonb, quality_pin boolean default false,
  ai_report jsonb, attachments jsonb default '[]',
  timeline jsonb default '[]',
  ts text, created_by text, price_plan text, notes text,
  created_at timestamptz default now()
);
create index if not exists idx_trips_tenant on trips(tenant_id);
create index if not exists idx_trips_status on trips(tenant_id, status);

-- Trucks
create table if not exists trucks (
  plate text not null,
  tenant_id text references tenants(id),
  type text, mfr text, cooling text, status text,
  valid boolean default true, remark text,
  cal_expiry text, flagged boolean default false,
  odometer_km numeric default 0,
  last_maint_km numeric default 0,
  maint_interval_km numeric default 10000,
  created_at timestamptz default now(),
  primary key (plate, tenant_id)
);

-- Maintenance tickets
create table if not exists maintenance (
  id text primary key,
  tenant_id text references tenants(id),
  truck text, description text,
  parts jsonb default '[]', status text default 'open',
  ts text, attachments jsonb default '[]',
  auto boolean default false, trip_id text,
  created_at timestamptz default now()
);
create index if not exists idx_maint_tenant on maintenance(tenant_id);

-- Audit log
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  tenant_id text references tenants(id),
  ts text, username text, role text,
  action text, detail text, trip_id text,
  created_at timestamptz default now()
);
create index if not exists idx_audit_tenant on audit_log(tenant_id);

-- Spare parts
create table if not exists spare_parts (
  id text primary key,
  tenant_id text references tenants(id),
  name text, sku text, qty numeric, min_qty numeric,
  unit text, cost numeric, supplier text, category text,
  created_at timestamptz default now()
);

-- Account manager assignments
create table if not exists am_assignments (
  id bigint generated by default as identity primary key,
  tenant_id text references tenants(id),
  am_name text, customer text,
  created_at timestamptz default now()
);

-- Customers
create table if not exists customers (
  id bigint generated by default as identity primary key,
  tenant_id text references tenants(id),
  name text not null,
  created_at timestamptz default now()
);
create index if not exists idx_customers_tenant on customers(tenant_id);

-- Invite codes (for org self-registration)
create table if not exists invite_codes (
  id text primary key,
  active boolean default true,
  used_by text default '',
  created_at timestamptz default now()
);

-- Generic app state (settings, invoices, fuel logs, PM schedules, …)
create table if not exists app_state (
  tenant_id text references tenants(id),
  key text not null,
  value text,
  updated_at timestamptz default now(),
  primary key (tenant_id, key)
);

-- ── Seed the default org ──────────────────────────────────────
insert into tenants (id, name, plan, active)
values ('instaport', 'InstaPort Logistics', 'enterprise', true)
on conflict (id) do nothing;

-- ══════════════════════════════════════════════════════════════
-- Row Level Security — allow anon key full access (app enforces
-- tenant separation itself). For production hardening, replace
-- with per-tenant policies + Supabase Auth.
-- ══════════════════════════════════════════════════════════════
alter table tenants enable row level security;
alter table users enable row level security;
alter table trips enable row level security;
alter table trucks enable row level security;
alter table maintenance enable row level security;
alter table audit_log enable row level security;
alter table spare_parts enable row level security;
alter table am_assignments enable row level security;
alter table customers enable row level security;
alter table invite_codes enable row level security;
alter table app_state enable row level security;

do $$
declare t text;
begin
  foreach t in array array['tenants','users','trips','trucks','maintenance','audit_log','spare_parts','am_assignments','customers','invite_codes','app_state']
  loop
    execute format('drop policy if exists anon_all on %I', t);
    execute format('create policy anon_all on %I for all using (true) with check (true)', t);
  end loop;
end $$;
